-- ============================================================
-- Project: Mini E-commerce Data Warehouse with PostgreSQL
-- File: 06_create_dimensions.sql
-- Purpose: Create and populate the dimensional tables
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Customer dimension
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.dim_customer (
    customer_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER UNIQUE,
    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT dim_customer_unknown_consistency CHECK (
        (is_unknown = TRUE AND customer_id IS NULL)
        OR
        (is_unknown = FALSE AND customer_id IS NOT NULL)
    )
);

COMMENT ON TABLE warehouse.dim_customer IS
    'Customer dimension containing one row per identified source customer.';

COMMENT ON COLUMN warehouse.dim_customer.customer_key IS
    'Warehouse surrogate key used by fact tables.';

COMMENT ON COLUMN warehouse.dim_customer.customer_id IS
    'Customer identifier provided by the source dataset.';

-- ------------------------------------------------------------
-- Product dimension
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.dim_product (
    product_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code TEXT NOT NULL UNIQUE,
    product_description TEXT,
    first_seen_at TIMESTAMP,
    last_seen_at TIMESTAMP,
    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE warehouse.dim_product IS
    'Product dimension containing one canonical row per stock code.';

COMMENT ON COLUMN warehouse.dim_product.product_description IS
    'Most frequent non-null description associated with the stock code.';

-- ------------------------------------------------------------
-- Country dimension
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.dim_country (
    country_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_name TEXT NOT NULL UNIQUE,
    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE warehouse.dim_country IS
    'Country dimension containing one row per normalized country value.';

-- ------------------------------------------------------------
-- Date dimension
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS warehouse.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE UNIQUE,
    calendar_year SMALLINT,
    calendar_quarter SMALLINT,
    month_number SMALLINT,
    month_name TEXT,
    year_month CHAR(7),
    week_of_year SMALLINT,
    day_of_month SMALLINT,
    day_of_week SMALLINT,
    day_name TEXT,
    is_weekend BOOLEAN,
    is_unknown BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT dim_date_unknown_consistency CHECK (
        (is_unknown = TRUE AND date_key = 0 AND full_date IS NULL)
        OR
        (is_unknown = FALSE AND date_key > 0 AND full_date IS NOT NULL)
    )
);

COMMENT ON TABLE warehouse.dim_date IS
    'Calendar dimension generated from the source transaction date range.';

COMMENT ON COLUMN warehouse.dim_date.date_key IS
    'Date identifier using the YYYYMMDD integer format.';

COMMENT ON COLUMN warehouse.dim_date.day_of_week IS
    'ISO day number from 1 for Monday to 7 for Sunday.';

-- ------------------------------------------------------------
-- Reset the dimensions before rebuilding them
-- ------------------------------------------------------------

TRUNCATE TABLE
    warehouse.dim_customer,
    warehouse.dim_product,
    warehouse.dim_country,
    warehouse.dim_date
RESTART IDENTITY CASCADE;

-- ------------------------------------------------------------
-- Unknown dimension members
-- ------------------------------------------------------------

INSERT INTO warehouse.dim_customer (
    customer_key,
    customer_id,
    first_seen_at,
    last_seen_at,
    is_unknown
)
VALUES (
    0,
    NULL,
    NULL,
    NULL,
    TRUE
);

INSERT INTO warehouse.dim_product (
    product_key,
    stock_code,
    product_description,
    first_seen_at,
    last_seen_at,
    is_unknown
)
VALUES (
    0,
    '[UNKNOWN]',
    'Unknown product',
    NULL,
    NULL,
    TRUE
);

INSERT INTO warehouse.dim_country (
    country_key,
    country_name,
    is_unknown
)
VALUES (
    0,
    '[UNKNOWN]',
    TRUE
);

INSERT INTO warehouse.dim_date (
    date_key,
    full_date,
    is_unknown
)
VALUES (
    0,
    NULL,
    TRUE
);

-- ------------------------------------------------------------
-- Populate the customer dimension
-- ------------------------------------------------------------

INSERT INTO warehouse.dim_customer (
    customer_id,
    first_seen_at,
    last_seen_at,
    is_unknown
)
SELECT
    customer_id,
    MIN(invoice_date) AS first_seen_at,
    MAX(invoice_date) AS last_seen_at,
    FALSE AS is_unknown
FROM staging.transactions
WHERE customer_id IS NOT NULL
GROUP BY customer_id
ORDER BY customer_id;

-- ------------------------------------------------------------
-- Populate the product dimension
-- ------------------------------------------------------------

WITH product_activity AS (
    SELECT
        stock_code,
        MIN(invoice_date) AS first_seen_at,
        MAX(invoice_date) AS last_seen_at
    FROM staging.transactions
    WHERE stock_code IS NOT NULL
    GROUP BY stock_code
),

description_frequency AS (
    SELECT
        stock_code,
        description,
        COUNT(*) AS description_count,
        MAX(invoice_date) AS last_description_date
    FROM staging.transactions
    WHERE stock_code IS NOT NULL
      AND description IS NOT NULL
    GROUP BY
        stock_code,
        description
),

ranked_descriptions AS (
    SELECT
        stock_code,
        description,
        ROW_NUMBER() OVER (
            PARTITION BY stock_code
            ORDER BY
                description_count DESC,
                last_description_date DESC,
                description ASC
        ) AS description_rank
    FROM description_frequency
)

INSERT INTO warehouse.dim_product (
    stock_code,
    product_description,
    first_seen_at,
    last_seen_at,
    is_unknown
)
SELECT
    product_activity.stock_code,
    ranked_descriptions.description,
    product_activity.first_seen_at,
    product_activity.last_seen_at,
    FALSE AS is_unknown
FROM product_activity
LEFT JOIN ranked_descriptions
    ON ranked_descriptions.stock_code = product_activity.stock_code
   AND ranked_descriptions.description_rank = 1
ORDER BY product_activity.stock_code;

-- ------------------------------------------------------------
-- Populate the country dimension
-- ------------------------------------------------------------

INSERT INTO warehouse.dim_country (
    country_name,
    is_unknown
)
SELECT DISTINCT
    country,
    FALSE AS is_unknown
FROM staging.transactions
WHERE country IS NOT NULL
ORDER BY country;

-- ------------------------------------------------------------
-- Populate the date dimension
-- ------------------------------------------------------------

WITH date_bounds AS (
    SELECT
        MIN(invoice_date::DATE) AS minimum_date,
        MAX(invoice_date::DATE) AS maximum_date
    FROM staging.transactions
),

calendar AS (
    SELECT
        GENERATE_SERIES(
            minimum_date,
            maximum_date,
            INTERVAL '1 day'
        )::DATE AS full_date
    FROM date_bounds
)

INSERT INTO warehouse.dim_date (
    date_key,
    full_date,
    calendar_year,
    calendar_quarter,
    month_number,
    month_name,
    year_month,
    week_of_year,
    day_of_month,
    day_of_week,
    day_name,
    is_weekend,
    is_unknown
)
SELECT
    TO_CHAR(full_date, 'YYYYMMDD')::INTEGER AS date_key,
    full_date,
    EXTRACT(YEAR FROM full_date)::SMALLINT AS calendar_year,
    EXTRACT(QUARTER FROM full_date)::SMALLINT AS calendar_quarter,
    EXTRACT(MONTH FROM full_date)::SMALLINT AS month_number,

    CASE EXTRACT(MONTH FROM full_date)::INTEGER
        WHEN 1 THEN 'January'
        WHEN 2 THEN 'February'
        WHEN 3 THEN 'March'
        WHEN 4 THEN 'April'
        WHEN 5 THEN 'May'
        WHEN 6 THEN 'June'
        WHEN 7 THEN 'July'
        WHEN 8 THEN 'August'
        WHEN 9 THEN 'September'
        WHEN 10 THEN 'October'
        WHEN 11 THEN 'November'
        WHEN 12 THEN 'December'
    END AS month_name,

    TO_CHAR(full_date, 'YYYY-MM') AS year_month,
    EXTRACT(WEEK FROM full_date)::SMALLINT AS week_of_year,
    EXTRACT(DAY FROM full_date)::SMALLINT AS day_of_month,
    EXTRACT(ISODOW FROM full_date)::SMALLINT AS day_of_week,

    CASE EXTRACT(ISODOW FROM full_date)::INTEGER
        WHEN 1 THEN 'Monday'
        WHEN 2 THEN 'Tuesday'
        WHEN 3 THEN 'Wednesday'
        WHEN 4 THEN 'Thursday'
        WHEN 5 THEN 'Friday'
        WHEN 6 THEN 'Saturday'
        WHEN 7 THEN 'Sunday'
    END AS day_name,

    EXTRACT(ISODOW FROM full_date)::INTEGER IN (6, 7) AS is_weekend,
    FALSE AS is_unknown
FROM calendar
ORDER BY full_date;

COMMIT;
